services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    volumes:
      - ./front:/app
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    working_dir: /app
    volumes:
      - ./back:/app
      - ./public/uploads:/app/public/uploads
    command: ["npm", "run", "develop"]
    ports:
      - "1337:1337"
    env_file: .env
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: ./data/data.db
      NODE_ENV: ${NODE_ENV}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
    depends_on: []